import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NextIntlClientProvider } from "next-intl";
import { getMessages } from "next-intl/server";
import Navbar from "@/component/Navbar/Navber";
import Provider from "../context/Provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Crime Report ",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const message = await getMessages();
  return (
    <NextIntlClientProvider messages={message}>
    <html lang="en">
      <body className={inter.className}>
        <Provider >
          <Navbar/>
          {children}
        </Provider>
      </body>
    </html>
    </NextIntlClientProvider>
  );
}
